### ISSUE TITLE
MIXED state is misreported as ALLOCATED

### ISSUE THREAD

**Issue by giovtorres** [gingergeeks/pyslurm#48] opened 2015-08-08 23:48 UTC
pyslurm is not reporting the correct node state for nodes in the MIXED state.  In this example, pyslurm reports the node is ALLOCATED...

>>> pyslurm.node().get()['cn0313']['node_state']
'ALLOCATED'

...while the slurm commands report the node is in the MIXED state:

$ scontrol show node cn0313 | grep -i state
   State=MIXED ThreadsPerCore=2 TmpDisk=6451 Weight=40

sinfo also reports the node in the MIXED state.  Tested wrong in both pyslurm version 14.11.0-0 and 14.11.5.

I am using SLURM 14.11.7, python 2.6.6 and Cython 0.22.1.

**Comment by gingergeeks** [comment] 2015-08-09 09:08
Thank you for the report. I clearly have some logic wrong there and will need to recheck it !

**Comment by gingergeeks** [comment] 2015-08-24 19:13
Sorry for the delay.....other priorities. I have rewritten the code slightly so it now reports correctly but I can see that more work is still needed to account for cluster and BG flags but this is working on my test code which I will commit as soon as I can to 14.11.x and 15.08.x.

    makalu:/home/mark/pyslurm # sinfo
    PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
    debug        up   infinite      1  down* shivling
    debug        up   infinite      1    mix makalu
    pbatch*      up      30:00      1  down* shivling
    pbatch*      up      30:00      1    mix makalu

The corresponding output in show in the examples/node_list.py for node makalu -

        sockets             : 1
        state               : MIXED
        threads             : 2
        tmp_disk            : 0
        total_cpus          : 6
        tres_fmt_str        : cpu=8,mem=1000
        version             : 15.08

I won't close this until the code is committed and you can test it.

**Comment by giovtorres** [comment] 2015-12-09 18:54
I must have missed this.  The reported states are better, but still broken.  I am now getting "+DRAIN" in addition to the actual state of the node.  It appears only on the non-default partition, if that has any significance.

For example:
```
scontrol show node cn2113 | grep State
   State=ALLOCATED ThreadsPerCore=1 TmpDisk=393 Weight=10
```

```
>>> pprint(nodes.get('cn2113').get("state"))
'ALLOCATED+DRAIN'
```

Here's a comparison of a node in our default partition:
```
scontrol -d show node cn0001 | grep State
   State=ALLOCATED ThreadsPerCore=2 TmpDisk=6451 Weight=40
```
```
>>> pprint(nodes.get('cn0001').get("state"))
'ALLOCATED'
```

**Comment by giovtorres** [comment] 2015-12-09 18:55
Forgot to mention, this is with the patch provided here: https://github.com/gingergeeks/pyslurm/files/56029/pyslurm.pyx.zip

**Comment by gingergeeks** [comment] 2015-12-09 19:03
Right, another one not put to bed yet :(

**Comment by gingergeeks** [comment] 2015-12-10 14:50
Giovanni, I'm unable to reproduce this at the moment using a job in either default or non-default partition. I believe it is happening I just can't generate the situation so I can examine the data. If I set the node to drain whilst it is running a job (default and non default partition) then that state is correctly marked as "ALLOCATED+DRAIN" but I cannot see that state when the node is only ALLOCATED. I will continue to try and force the error.

**Comment by giovtorres** [comment] 2015-12-10 17:31
This is what I found... If I add the following print statements:
```
            print "  drain_str BEFORE:", drain_str
            if (my_state & NODE_STATE_DRAIN):
                print "  im here"
                my_state &= (~NODE_STATE_DRAIN)
                drain_str = "+DRAIN"
```

This is what I get on a node whose state is ALLOCATED:

```
  drain_str BEFORE: +DRAIN
```

"im here" does not get printed.  Any ideas?

**Comment by gingergeeks** [comment] 2015-12-10 17:37
I will go through the code again.

**Comment by giovtorres** [comment] 2015-12-10 17:41
Thanks.  

If I comment out #drain_str = "+DRAIN", then drain_str doesn't get set.  Makes sense.  

But, I can't see how/why 'drain_str' gets set before its reassignment.  The only line prior to that one that references 'drain_str' is its declaration: char *drain-str = "".

**Comment by gingergeeks** [comment] 2015-12-10 21:01
Giovanni,
              Please can you give this out of band zipped pyslurm.pyx file a test. You were observant regarding the state strings not being initialised, they are now :) My tests show nodes in MIXED and ALLOCATED state with no attached +DRAIN string.

Mark
[pyslurm.pyx.zip](https://github.com/gingergeeks/pyslurm/files/58719/pyslurm.pyx.zip)

**Comment by giovtorres** [comment] 2015-12-11 00:09
This works perfectly now.  Thanks Mark.

**Comment by gingergeeks** [comment] 2015-12-11 21:58
Closing, reopen if I mess this up again. Thank you for your help

**Closed by gingergeeks** 2015-12-11 21:58 UTC
