### ISSUE TITLE
Use of licenses (-L) makes pyslurm job.get() crashing

### ISSUE THREAD

**Issue by laparn** [gingergeeks/pyslurm#34] opened 2013-06-03 14:48 UTC
In starting the following job (after having created a license test in slurm.conf) : 
srun -L test -N 1 ./wait-arg.sh 240

I get the following error with pyslurm : 
python
Python 2.7.3 (default, Apr 10 2013, 06:20:15) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyslurm
>>> job=pyslurm.job()
>>> a=job.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm.pyx", line 1588, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:20271)
  File "pyslurm.pyx", line 1638, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:20709)
  File "pyslurm.pyx", line 3670, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:41420)
ValueError: need more than 1 value to unpack

This occured both on Ubuntu 12.04 (slurm 2.5.0) and on centos 6.3 (slurm 2.5.something) with pyslurm compiled from the trunk.

If I add in pyslurm.pyx, the following line : 
print(("debug __get_licenses %s",alist[i]))
on line 3669 of pyslurm.pyx, then I have the resulting output  : 
arnaud@D3550:/usr/local$ python
Python 2.7.3 (default, Apr 10 2013, 06:20:15) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("/usr/local/lib/python2.7/dist-packages/pyslurm-2.5.6_1")
>>> import pyslurm
>>> a=pyslurm.job()
>>> b=a.get()
('debug __get_licenses %s', 'test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm.pyx", line 1588, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:20273)
  File "pyslurm.pyx", line 1638, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:20711)
  File "pyslurm.pyx", line 3670, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:41430)
ValueError: need more than 1 value to unpack

So we see that pyslurm waits for a string formatted as xxxx*number . And in my configuration file, I have : Licenses=test*2,test2
so at least the test*2 should be ok. So it is the reading of this string that is buggy.

**Comment by giovtorres** [comment] 2015-08-10 15:09
I started seeing the same thing today.  I'm using:

SLURM 14.11.7
pyslurm 14.11.5
Cython 0.22.1
Python 2.6.6

```
>>> pyslurm.job()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 1678, in pyslurm.pyslurm.job.__cinit__ (pyslurm/pyslurm.c:22315)
  File "pyslurm/pyslurm.pyx", line 1793, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:23526)
  File "pyslurm/pyslurm.pyx", line 1854, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:24066)
  File "pyslurm/pyslurm.pyx", line 4216, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:50273)
ValueError: need more than 1 value to unpack
```

**Comment by gingergeeks** [comment] 2015-08-10 17:36
Hmm, works for my test case. Can you send the appropriate output line from Slurm for the job ?

**Comment by giovtorres** [comment] 2015-08-10 17:44
I wasn't running any jobs.  I just opened the interpreter and ran the following to reproduce the error:

```
>>> import pyslurm
>>> pyslurmjob = pyslurm.job()
```

It occurs when there is one or more licenses checked out.

**Comment by gingergeeks** [comment] 2015-08-10 17:46
Right I will try again...thank you again for your time.

**Comment by giovtorres** [comment] 2015-08-10 18:16
Looks like on line 4209 of pyslurm.pyx, I see alist is a list of strings, where the strings match the license name.  The strings do not have a split_char in them.

```
alist = ['matlab']
```

From the code, it appears alist should look like this:

```
alist = ['matlab:4']
```

This is why I am getting the unpacking error when trying to split the string.

**Comment by gingergeeks** [comment] 2015-08-10 20:07
When I check the return it is a dictionary with the number of requested/used licenses for the job. 

```python
   >>> import pyslurm
   >>> pyslurmjob = pyslurm.job()
   {u'lstc': '4'}
```

**Comment by giovtorres** [comment] 2015-08-10 20:13
Hmm.  Do you have any suggestions I could use to debug further on my end?

**Comment by gingergeeks** [comment] 2015-08-10 20:17
What's the output of "scontrol show lic" ?

**Comment by giovtorres** [comment] 2015-08-10 20:18
```
LicenseName=idl
    Total=6 Used=0 Free=6 Remote=no
LicenseName=matlab-stat
    Total=1 Used=0 Free=1 Remote=no
LicenseName=matlab-pde
    Total=1 Used=0 Free=1 Remote=no
LicenseName=matlab-compiler
    Total=1 Used=0 Free=1 Remote=no
LicenseName=matlab
    Total=4 Used=0 Free=4 Remote=no
```

**Comment by gingergeeks** [comment] 2015-08-10 20:31
OK, lets display the license string in the __get_licenses routine and rebuild/install, add something similar to the following.

```python
        if (licenses is NULL):
                return licDict

        print "LIC %s" % licenses

        cdef:
                list alist = slurm.listOrNone(licenses, ',')
                int listLen = len(alist)
```

**Comment by giovtorres** [comment] 2015-08-10 20:35
```
LIC matlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 1678, in pyslurm.pyslurm.job.__cinit__ (pyslurm/pyslurm.c:22331)
    self.get()
  File "pyslurm/pyslurm.pyx", line 1793, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:23542)
    self.__get()
  File "pyslurm/pyslurm.pyx", line 1854, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:24082)
    Job_dict[u'licenses'] = __get_licenses(self._job_ptr.job_array[i].licenses)
  File "pyslurm/pyslurm.pyx", line 4218, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:50304)
    key, value = alist[i].split(split_char)
ValueError: need more than 1 value to unpack
```

**Comment by gingergeeks** [comment] 2015-08-10 20:38
So you are not getting a value for "matlab", I get for example "lstc:4". I
need to dig into the API a little to make sure I'm not missing something,
I'll get back to you shortly.

**Comment by giovtorres** [comment] 2015-08-10 20:39
Yup, no value for number of licenses, just the name.  Thanks!

**Comment by gingergeeks** [comment] 2015-08-10 20:48
I have an example license monitor program similar to "scontrol show lic" you can run examples/licenses.py

**Comment by giovtorres** [comment] 2015-08-10 20:58
That shows correctly.  I checked out 1 matlab license, then released it.  

```
$ ./licenses.py 
[u'matlab-stat', u'idl', u'matlab-compiler', u'matlab', u'matlab-pde']
State last updated : Mon Aug 10 20:52:54 2015
--------------------------------------------------------------------------------
matlab-stat :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
idl :
	available         : 6
	in_use            : 0
	remote            : 0
	total             : 6
--------------------------------------------------------------------------------
matlab-compiler :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
matlab :
	available         : 4
	in_use            : 0
	remote            : 0
	total             : 4
--------------------------------------------------------------------------------
matlab-pde :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
*****************
[u'matlab-stat', u'idl', u'matlab-compiler', u'matlab', u'matlab-pde']
State last updated : Mon Aug 10 20:53:37 2015
--------------------------------------------------------------------------------
matlab-stat :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
idl :
	available         : 6
	in_use            : 0
	remote            : 0
	total             : 6
--------------------------------------------------------------------------------
matlab-compiler :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
matlab :
	available         : 3
	in_use            : 1
	remote            : 0
	total             : 4
--------------------------------------------------------------------------------
matlab-pde :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
*****************
*****************
[u'matlab-stat', u'idl', u'matlab-compiler', u'matlab', u'matlab-pde']
State last updated : Mon Aug 10 20:55:29 2015
--------------------------------------------------------------------------------
matlab-stat :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
idl :
	available         : 6
	in_use            : 0
	remote            : 0
	total             : 6
--------------------------------------------------------------------------------
matlab-compiler :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
matlab :
	available         : 4
	in_use            : 0
	remote            : 0
	total             : 4
--------------------------------------------------------------------------------
matlab-pde :
	available         : 1
	in_use            : 0
	remote            : 0
	total             : 1
--------------------------------------------------------------------------------
*****************
^CExiting....
```

However, while the license was checked out, pyslurm.job() still fails:

```
>>> pyslurm.job()
LIC matlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 1678, in pyslurm.pyslurm.job.__cinit__ (pyslurm/pyslurm.c:22331)
    self.get()
  File "pyslurm/pyslurm.pyx", line 1793, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:23542)
    self.__get()
  File "pyslurm/pyslurm.pyx", line 1854, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:24082)
    Job_dict[u'licenses'] = __get_licenses(self._job_ptr.job_array[i].licenses)
  File "pyslurm/pyslurm.pyx", line 4218, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:50304)
    key, value = alist[i].split(split_char)
ValueError: need more than 1 value to unpack
```

**Comment by gingergeeks** [comment] 2015-08-10 21:10
On my simple test vmware I don't have any actual license servers so I'm testing with a simple config. How have you defined licenses in the config ? 

```text
Licenses=lstc-test*4,lstc-new*6,totalview*8
```

so I wonder if they is possibly a situation where no value is returned whilst we query it during an acutal checkout. I could test for a no value situation but we would need to return a key value of some sort.

**Comment by giovtorres** [comment] 2015-08-10 23:10
There are several references to __get_licenses in various classes.  I tried pyslurm.config() and it does not give me the same error as pyslurm.job().

Here is the license output I have from scontrol. 
```
$ scontrol show config | grep -i license
Licenses                = matlab:4,matlab-compiler:1,matlab-pde:1,matlab-stat:1,idl:6
LicensesUsed            = idl:0/6,matlab-stat:0/1,matlab-pde:0/1,matlab-compiler:0/1,matlab:1/4
```

I left the print statement in the __get_licenses function.  Interestingly enough, pyslurm.config.get() makes a call to __get_licenses and it does print a proper dictionary:

```
>>> pyslurm.config().get()
LIC matlab:4,matlab-compiler:1,matlab-pde:1,matlab-stat:1,idl:6
LIC idl:0/6,matlab-stat:0/1,matlab-pde:0/1,matlab-compiler:0/1,matlab:1/4
{u'fast_schedule': True, u'suspend_exc_parts': [], u'priority_decay_hl': 604800, u'state_save_location': ...
```

For some reason,  ```Job_dict[u'licenses'] = __get_licenses(self._job_ptr.job_array[i].licenses)``` causes a problem when a license is checked out.  I wonder if it has something to do with the ":" separator?

Could you try changing your Licenses config to use ":" instead of "*" and see if you can replicate the error with pyslurm.job()?

Thanks!

**Comment by gingergeeks** [comment] 2015-12-08 22:57
I think this long resolved when I changed to you requested method. Please reopen if still an issue

**Comment by giovtorres** [comment] 2015-12-09 15:57
I don't recall seeing any code change for this.  It still occurs.

I use the 14.11.5 branch.  If there are no licenses checked out, pyslurm.job() works just fine.  If, however, there are one or more licenses checked out, __get_licenses() throws an exception, same as describe above.

```
>>> pyslurmjob = pyslurm.job()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 1678, in pyslurm.pyslurm.job.__cinit__ (pyslurm/pyslurm.c:22341)
  File "pyslurm/pyslurm.pyx", line 1793, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:23552)
  File "pyslurm/pyslurm.pyx", line 1854, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:24092)
  File "pyslurm/pyslurm.pyx", line 4260, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:50889)
ValueError: need more than 1 value to unpack
```

I get around it by commenting out that line and recompiling.

**Comment by gingergeeks** [comment] 2015-12-09 15:59
OK, so I will get it fixed (thought I had !)

**Comment by gingergeeks** [comment] 2015-12-10 18:51
Giovanni,
               This is one, I cannot recreate at the moment as it appears to work for me. Can you provide me with an updated trace from the latest PySlurm-14.11.5 download and the appropriate lines from the slurm config for the licenses definitions. I will continue to try to make it fail.

Mark

**Comment by gingergeeks** [comment] 2015-12-10 20:06
Giovanni,
              Can you give this gzipped out-of-band pyslurm.pyx a test. You were observant to the fact that the various state strings were not being set correctly.

Mark

**Comment by giovtorres** [comment] 2015-12-11 00:14
Here is the traceback:
```
>>> pyslurmjob = pyslurm.job()
LIC sas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyslurm/pyslurm.pyx", line 1678, in pyslurm.pyslurm.job.__cinit__ (pyslurm/pyslurm.c:22343)
  File "pyslurm/pyslurm.pyx", line 1793, in pyslurm.pyslurm.job.get (pyslurm/pyslurm.c:23554)
  File "pyslurm/pyslurm.pyx", line 1854, in pyslurm.pyslurm.job.__get (pyslurm/pyslurm.c:24094)
  File "pyslurm/pyslurm.pyx", line 4265, in pyslurm.pyslurm.__get_licenses (pyslurm/pyslurm.c:50919)
ValueError: need more than 1 value to unpack
```

Here is the license config:
```
Licenses=matlab:16,matlab-compiler:1,matlab-pde:1,matlab-stat:1,matlab-bio:1,matlab-curve:1,matlab-image:3,matlab-neural:1,matlab-opt:2,matlab-pde:1,matlab-signal:3,matlab-stat:4,matlab-symb:1,matlab-wave:1,idl:6,sas:48
```

Looking at the previous comments, your license config uses "*" as the delimiter.  Could you change them to ":" to see if that will reproduce the issue on your end?

Thanks,
Giovanni

**Comment by gingergeeks** [comment] 2015-12-11 22:05
My test config is using ":" as the the delimiter, at the moment I still do not get the issue but I will track it down.

**Comment by gingergeeks** [comment] 2015-12-11 22:49
I can reproduce the issue in one situation. Are you submitting a license request in a job without the number as in "#SBATCH -L lstc" instead of " #SBATCH -L lstc:1" ?

**Comment by giovtorres** [comment] 2015-12-12 00:39
I guess I should have mentioned how users submit jobs that requests licenses.  Our users submit as follows:

```
sbatch --license=matlab jobscript.sh
```
or
```
sbatch --license=matlab,matlab-stat jobscript.sh
```
Our users typically do not specify a license count at checkout, just the name of the license.  We would only specify a number when more than one license is desired or required for an application.  I guess 1 is the default count if not specified with sbatch?

**Comment by gingergeeks** [comment] 2015-12-12 16:57
Giovanni,
               I've committed a change to the 14.11.5 branch in __get_licenses to handle the situation above. Please could you test and then me know if it is OK, when you are happy I will make the change to the 14.11 and 15.x branches.

Mark

**Comment by giovtorres** [comment] 2015-12-14 18:32
Hi Mark,

This looks good!  No tracebacks when calling pyslurm.job() even when licenses are checked out and pyslurm.config().get().get("licenses_used") shows the correct used/available count.

Thanks,
Giovanni

**Comment by gingergeeks** [comment] 2015-12-14 19:59
Giovanni,
               Thank you for checking it out, I will close this ticket and port this change to the 15.x and the rest of the 14.x branches. I could also backport to the 2.6 branch but I'm not sure this people are using it still.

Mark

**Closed by gingergeeks** 2015-12-14 19:59 UTC
